if __name__ == '__main__':
    mapping = {
        'y': 'a',
        'x': 'b',
        'm': 'c',
        'd': 'd',
        'a': 'e',
        'c': 'f',
        'i': 'g',
        'k': 'h',
        'n': 'i',
        't': 'j',
        'j': 'k',
        'h': 'l',
        'q': 'm',
        'l': 'n',
        'g': 'o',
        'o': 'p',
        'u': 'q',
        'f': 'r',
        's': 's',
        'z': 't',
        'p': 'u',
        'w': 'v',
        'b': 'w',
        'r': 'x',
        'e': 'y',
        'v': 'z',
        'Y': 'A',
        'X': 'B',
        'M': 'C',
        'D': 'D',
        'A': 'E',
        'C': 'F',
        'I': 'G',
        'K': 'H',
        'N': 'I',
        'T': 'J',
        'J': 'K',
        'H': 'L',
        'Q': 'M',
        'L': 'N',
        'G': 'O',
        'O': 'P',
        'U': 'Q',
        'F': 'R',
        'S': 'S',
        'Z': 'T',
        'P': 'U',
        'W': 'V',
        'B': 'W',
        'R': 'X',
        'E': 'Y',
        'V': 'Z'
    }
    target = 'EaFnjISplhFviDhwFbEjRjfIBBkRyY'
    original = ""
    for i in target:
        original += mapping[i]
    print(original)
